"""empty message

Revision ID: 2eda29a60246
Revises: b54daf03d8f3
Create Date: 2025-02-22 19:16:21.869472

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2eda29a60246"
down_revision = "b54daf03d8f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Albums", schema=None) as batch_op:
        batch_op.alter_column(
            "release_year",
            existing_type=sa.DATE(),
            type_=sa.Integer(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Albums", schema=None) as batch_op:
        batch_op.alter_column(
            "release_year",
            existing_type=sa.Integer(),
            type_=sa.DATE(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
