"""empty message

Revision ID: b54daf03d8f3
Revises: 
Create Date: 2025-02-01 17:23:02.977992

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b54daf03d8f3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Artists")
    # ### end Alembic commands ###
